name: Test
on:
  - push

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }} @ ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "2.7"
          - "3.4"
          - "3.5"
          - "3.6"
          - "3.7"
          - "3.8"
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install test requirements
        run: make install-test-requirements
      - name: Test
        run: make test
