name: Test
on:
  push:
    paths:
      - "*.py"
      - "setup.*"
      - ".github/workflows/pytest.yaml"

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "2.7"
          - "3.4"
          - "3.5"
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
    container: python:${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install test requirements
        run: make install-test-requirements
      - name: Test
        run: make test
